### ISSUE TITLE
Clarifier les droits de réutilisation

### ISSUE THREAD

**Issue by DavidBruant** [etalab/data-codes-sources-fr#1]
A la fin du Readme, on peut lire : 

> © 2018 Direction interministérielle du numérique et du système d’information et de communication de l’État, Antoine Augusti, Bastien Guerry.
>
> © 2018 Les autres contributeurs dans la liste est accessible via l’historique du dépôt.

Le repo contient une licence MIT non-mentionnée dans ce bloc (cette licence ne mentionne que Antoine Augusti, ce qui n'est pas cohérent avec le readme)

Aussi, est-ce qu'il s'agit d'un document administratif au sens du [Code des relations entre le public et l'administration](https://www.legifrance.gouv.fr/affichCode.do;jsessionid=12A6050D30BDE6AE5798017413481657.tplgfr31s_2?cidTexte=LEGITEXT000031366350&dateTexte=20190125) (ce qui impliquerait l'application du Livre 3 Titre II) ?
Je n'ai pas de connaissance à ce niveau de détail, mais j'ai l'impression que c'est assez équivalent à la licence MIT avec une petite contrainte en plus : 

>  la réutilisation des informations publiques est soumise à la condition que ces dernières ne soient pas altérées, que leur sens ne soit pas dénaturé et que leurs sources et la date de leur dernière mise à jour soient mentionnées

[Article L322-1](https://www.legifrance.gouv.fr/affichCodeArticle.do;jsessionid=12A6050D30BDE6AE5798017413481657.tplgfr31s_2?idArticle=LEGIARTI000032255220&cidTexte=LEGITEXT000031366350&dateTexte=20190125)

ce qui est un poil plus contraignant que la licence MIT

**Comment by AntoineAugusti** [comment]
Bonjour,

Le dépôt vient d'être migré sous l'organisation Etalab, ce qui explique cette différence dans le README. C'est explicité dans https://github.com/etalab/data-codes-sources-fr/commit/6ed5850ae1ec84e32aa6133a5e58b68e7ac2aa52.

En résumé, en accord avec https://www.data.gouv.fr/fr/licences :
- code source sous licence MIT
- données sous licence ouverte 2.0

**Comment by AntoineAugusti** [comment]
Commit https://github.com/etalab/data-codes-sources-fr/commit/6ed5850ae1ec84e32aa6133a5e58b68e7ac2aa52
