### ISSUE TITLE
Get the archived status (boolean) of each repository

### ISSUE THREAD

**Issue by bzg** [etalab/data-codes-sources-fr#15]
See https://developer.github.com/v3/repos/#get and look for `archived`.

**Comment by AntoineAugusti** [comment]
It seems very specific to GitHub for now. Is it needed?

**Comment by bzg** [comment]
GitLab also has a notion of "archiving" a project - I don't know whether this information is accessible through the GitLab API though.

Even if we have this information just for GitHub, yes, I think it is needed. It helps us to have a notion of +non-forks +non-archived projects.

**Comment by AntoineAugusti** [comment]
Done in https://github.com/etalab/data-codes-sources-fr/commit/f8dcc349c756d960e14ba78e208ed9d2a84836c9

**Comment by bzg** [comment]
Thanks!
