### ISSUE TITLE
Errors on some SWH URLS

### ISSUE THREAD

**Issue by bzg** [etalab/data-codes-sources-fr#24]
There are 404 and 500 errors on some Software Heritage URLs.

E.g. this [link](https://archive.softwareheritage.org/browse/origin/https://github.com/SocialGouv/code-du-travail-backoffice/directory/) (404) and this [one](https://archive.softwareheritage.org/browse/origin/https://github.com/cea-sec/miasm/directory/) (500).

The 404 error says:

> NotFoundExc: No snapshot associated to the visit of origin https://github.com/SocialGouv/code-du-travail-backoffice on 20 August 2019, 00:34 UTC 

The 500 error says:

> QueryCanceledError: canceling statement due to statement timeout

Note that a 500 error is also returned randomly/temporarily on some other repositories.

![swh-404-error](https://user-images.githubusercontent.com/63500/65511236-fec1eb80-ded6-11e9-9dc1-14984eca9723.png)
![swh-500-error](https://user-images.githubusercontent.com/63500/65511242-02557280-ded7-11e9-9b62-8313f466d218.png)

**Comment by AntoineAugusti** [comment]
Do you have URLs who respond with a random 500 on SWH side? It's likely on their side as it's a 500 error but could help them troubleshoot the underlying issue.

**Comment by AntoineAugusti** [comment]
I'm investigating this origin: https://github.com/SocialGouv/code-du-travail-backoffice. The SWH directory URL returns a 404: https://archive.softwareheritage.org/browse/origin/https://github.com/SocialGouv/code-du-travail-backoffice/directory/.

## Investigation
Is the origin listed in SWH?
API documentation: https://archive.softwareheritage.org/api/1/origin/

I get a 200 OK
```
$ curl -I "https://archive.softwareheritage.org/api/1/origin/https://github.com/SocialGouv/code-du-travail-backoffice/get/"
HTTP/1.1 200 OK
```
Origin is known from SWH.

There is only 1 visit, which is partial (unsure what it means): https://archive.softwareheritage.org/api/1/origin/https://github.com/SocialGouv/code-du-travail-backoffice/visits/

### Questions
Unclear about why the directory returns a 404 then.
How to know the directory URL for an origin?

**Comment by AntoineAugusti** [comment]
Regarding the second origin, https://archive.softwareheritage.org/browse/origin/https://github.com/cea-sec/miasm/directory/, you reported a 500, I get a 200 OK right now. 500 is an error on SWH side, don't know what happened.

**Comment by AntoineAugusti** [comment]
Investigating a full snapshot for no files available on SWH for origin https://gitlab.inria.fr/compass/compass.

Directory URL: https://archive.softwareheritage.org/browse/origin/https://gitlab.inria.fr/compass/compass showing "The snapshot associated to the visit of origin https://gitlab.inria.fr/compass/compass on 23 August 2019, 13:50 UTC is empty !"

Unclear about why, the [visits](https://archive.softwareheritage.org/api/1/origin/https://gitlab.inria.fr/compass/compass/visits/) is reported as full and the project [had commits](https://gitlab.inria.fr/compass/compass/commits/master) before 23 August 2019. Maybe it was not pushed to Gitlab at this point?

**Comment by AntoineAugusti** [comment]
According to the following sequence diagrams, SWH stopped at inserting the origin in SWH and the loader task was never picked, hence the absence of snapshots.

https://docs.softwareheritage.org/devel/architecture.html#tasks

Don't know why.

**Comment by bzg** [comment]
I cannot reproduce the errors above, I'm closing this issue.

**Comment by AntoineAugusti** [comment]
Not too fast. I think some repos which are currently marked as archived here are partially archived because of some bugs on SWH's side. We've seen in the past partially archived / 404 / 500
