### ISSUE TITLE
Use pushed_at instead of updated_at

### ISSUE THREAD

**Issue by bzg** [etalab/data-codes-sources-fr#25]
Currently we use `updated_at` from the GitHub API - I don't know the equivalent in GitLab's API.

While browsing https://code.etalab.gouv.fr I find it confusing: an "update" can be anything from a commit to a reply in an issue.

I suggest to use `pushed_at` from GitHub's API instead, iff there is an equivalent in GitLab's API.

WDYT?

PS: I found some explanations [here](https://stackoverflow.com/questions/15918588/github-api-v3-what-is-the-difference-between-pushed-at-and-updated-at).

**Comment by AntoineAugusti** [comment]
There is no equivalent on GitLab's API according to the documentation.

After regarding your StackOverflow question, this bit is interesting:
> `pushed_at` will be updated any time a commit is pushed to any of the repository's branches.

As there is no equivalent on Gitlab side and I don't see a clear benefit to introduce different meanings between Gitlab and GitHub, I'd be in favor of keeping it as it is right, `updated_at` which means the latest activity.

We could also introduce a new column, `pushed_at` which could be filled for GitHub and be `None` for Gitlab. I don't see that as an improvement.

What do you think?

**Comment by bzg** [comment]
Let's keep it as it is.

If there is a place where we can make requests to GitLab's API, maybe we can suggest them to implement this?

**Comment by AntoineAugusti** [comment]
Okay, I'm closing this issue.

I'll not go ask this to GitLab but feel free to do it if you're interested. I understand it could be of interest.

**Comment by bzg** [comment]
Sorry, re-opening.

From reading [this](https://gitlab.com/gitlab-org/gitlab-foss/merge_requests/11896) and [this](https://gitlab.com/gitlab-org/gitlab-foss/issues/42815) issues, it looks like we missed the `last_activity_at` property.

I can't seem to find the proper definition of `last_activity_at` but it looks like GitLab `last_activity_at` is the best equivalent to GitHub's `pushed_at`, while `updated_at` have roughly the same meaning on both platforms.

What do you think?

**Comment by AntoineAugusti** [comment]
I can certainly add a new column with `last_activity_at` from GitLab and `pushed_at` from GitHub. What would be an appropriate name for this? In French.

**Comment by bzg** [comment]
I suggest `derniere_modification`.

**Comment by AntoineAugusti** [comment]
Implementation is in #30. GitLab only exposes `created_at` and `last_activity_at`, which means `last_activity_at` will be in 2 columns for GitLab. Not sure this is an appropriate way to solve this issue.

**Comment by bzg** [comment]
Not sure too.

Btw, sorry I was confused by the presence od `updated_at` on other aspects of GitLab's API.

I've created an issue on GitLab suggesting to [implement a pushed_at equivalent](https://gitlab.com/gitlab-org/gitlab/issues/33475).

Still, we can leave it that way: having both `derniere_mise_a_jour` and `derniere_modification` can be helpful in the future, even if the current implementation is not semantically sound.

**Comment by AntoineAugusti** [comment]
PR has been merged. Closing.
