### ISSUE TITLE
Collect all groups from gitlab.inria.fr

### ISSUE THREAD

**Issue by bzg** [etalab/data-codes-sources-fr#26]
It looks like we receive only groups starting with a, b or c. As of today:

> ACG
> AlgebraicGeometricModeling
> Alpha
> andiamo
> CAPES-Math
> cidre-public
> comprise
> ClassCode
> Codes
> compass
> CompCert
> Conferences
> coqinterval

Why? There are probably a lot more groups on `gitlab.inria.fr`. Do we hit an API limit?

**Comment by AntoineAugusti** [comment]
As it's in alphabetical order, it's likely an API limit we're hitting. I'll report here after investigating.

**Comment by ax1036** [comment]
> As it's in alphabetical order, it's likely an API limit we're hitting. I'll report here after investigating.

May help: https://gitlab.inria.fr/help/api/README.md#pagination

**Comment by AntoineAugusti** [comment]
Currently, I try to find all public groups and then move on to find all public projects from these publics groups.

- [Related code](https://github.com/etalab/data-codes-sources-fr/blob/568ce363bc1d8cfae05186052ec24a1b6838da81/platforms.py#L62-L71)
- [API documentation for groups](https://docs.gitlab.com/ee/api/groups.html)

The INRIA GitLab endpoint [`/groups`](https://gitlab.inria.fr/api/v4/groups) returns only 20 publics groups. From these, we find currently 29 projects.

Maybe I'm missing something about what would be the proper way to find all public groups and projects for a self-hosted GitLab instance.

**Comment by neurolit** [comment]
API responses are paginated. If you look into the HTML headers:

x-next-page | 2
x-page | 1
x-per-page | 20
x-total | 1290
x-total-pages | 65

It means that there are 1290 projects, 20 by 20. If you want the next 20 projects, you need to add a _page_ parameter to the URL: https://gitlab.inria.fr/api/v4/groups?page=2 and so on, as there are 65 pages.

There shouldn't be any API limit for public projects.

**Comment by bzg** [comment]
Thanks @neurolit - I hope we can fix this soon and collect repositories from those 1290 projects!

**Comment by AntoineAugusti** [comment]
Thanks @neurolit and @ax1036. I missed the pagination documentation. I looked at the first response in a browser tab and did not see a key for next URL. My bad for not looking at HTTP headers.

PR #36 should fix the thing and collect appropriately repositories.

**Comment by bzg** [comment]
There was a glitch in the frontend, preventing all the repositories to be correctly displayed.

This is fixed now, we list 3422 repositories so far.  Thanks to both of you!
