### ISSUE TITLE
Numbers in the /Chiffres tabset

### ISSUE THREAD

**Issue by pachevalier** [etalab/data-codes-sources-fr#28]
In the /Chiffres tabset, I see 239 repos for Etalab but in the /Organisations tabset, I've got 219 on Github and 31 on Framagit. 

How do you get the number in the /Chiffres tabset ? Do you dedupe mirror repositories ?

**Comment by AntoineAugusti** [comment]
This done in pandas and not deduped by platform for now. If you're familiar with pandas, this could be fixed easily.

https://github.com/etalab/data-codes-sources-fr/blob/ce6917383fe831429105186d607adc9ef333350a/stats.py#L16-L22

**Comment by AntoineAugusti** [comment]
Related to https://github.com/etalab/codegouvfr/issues/41

**Comment by bzg** [comment]
> But by tweaking this code, we could generate a JSON by org name + platform, something like

Yes, this would be better.

**Comment by AntoineAugusti** [comment]
I've implemented this in #29. Let me know when I can deploy this, you'll need to adapt your frontend code as the JSON structure changes

**Comment by bzg** [comment]
Thanks for implementing this. You can safely switch to it now.

**Comment by AntoineAugusti** [comment]
Merged the PR. It'll be available on the API side in a few hours.
