### ISSUE TITLE
New est_miroir property?

### ISSUE THREAD

**Issue by bzg** [etalab/data-codes-sources-fr#35]
Looking at the API of gitea, I see they indicate if the repository is a mirror.

I don't know whether we have this kind of information for GitHub and GitLab, but maybe that would be interesting.

WDYT?

**Comment by AntoineAugusti** [comment]
GitHub seems to have it in a `mirror_url` field. https://developer.github.com/v3/repos/#list-organization-repositories

Can you find a repository which is a mirror on GitHub? I'm curious to see what it looks it in the UI and on the API side

**Comment by bzg** [comment]
Here is an example mirror repo (not from french public sector, tho): https://github.com/OpenMage/magento-mirror

I could not find a mirror among repos listed at code.etalab.gouv.fr, so we probably don't want to make our `json` heavier just for this.

**Comment by AntoineAugusti** [comment]
Okay, I'm closing this for now and we can reopen this later.
