### ISSUE TITLE
No need to include software_heritage_url in data/

### ISSUE THREAD

**Issue by bzg** [etalab/data-codes-sources-fr#37]
The `software_heritage_url` is now built programmatically from the frontend.

I suggest we remove `software_heritage_url` from the generated data, it will spare each user 300K of content downloading.

PS: My understanding from reading your code is that you use `software_heritage_url` to set `software_heritage_exists`, so I don't suggest to remove `software_heritage_url` altogether.

**Comment by AntoineAugusti** [comment]
The data exposed through the API is also available as open data. This is the same data.

Removing this attribute is fine for the frontend, not for the dataset. Not sure it's a good idea to have a different schema for the API and the raw data, yet.

This is related to https://github.com/etalab/codegouvfr/issues/52 according to me. It shows an underlying problem in pagination / dataset size.

**Comment by bzg** [comment]
I understand the need to expose all the data with explicit names on the API side.

As long as there is no way to perform a search through the API/backend, the frontend still needs to collect the complete set of data.

I have optimized the code.etalab.gouv.fr application by collecting/transforming/exposing data from my backend: the size of the data downloaded on the frontend is now reduced by 54% (1.2MO vs 2.6MO), it feels more reactive.

I'm closing this issue but feels free to comment further.
