### ISSUE TITLE
Invalid GitLab avatar_url

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/data-codes-sources-fr#38]
Caught by a data report, example: https://goodtables.io/github/etalab/data-codes-sources-fr/jobs/867

`avatar_url` is not a URI, hence the error.

## Investigation
- Group URL shows an invalid avatar, with a 404: https://gitlab.inria.fr/flowvr
- API shows an invalid URI as well: https://gitlab.inria.fr/api/v4/groups/cedar

**Comment by bzg** [comment]
Should we close this issue?

**Comment by AntoineAugusti** [comment]
Yes, it should have been fixed in the previous commit
