### ISSUE TITLE
Duplicate orgs and repos on gitlab.inria.fr

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/data-codes-sources-fr#39]
A few orgs and repos are duplicates or gitlab.inria.fr for an unknown reason yet.

Investigate why it happens for a few orgs or deduplicate in the end.

**Comment by bzg** [comment]
I cannot find duplicates anymore. Can we close this issue?

**Comment by AntoineAugusti** [comment]
No. It's still present: https://goodtables.io/github/etalab/data-codes-sources-fr/jobs/1093

How did you check for the absence of duplicates?

**Comment by bzg** [comment]
> How did you check for the absence of duplicates?

Well, by hand.  Testing more carefully with

```
(def repos (map :r (json/parse-string (slurp "data/repos.json") true)))
(def orgas (map :o (json/parse-string (slurp "data/orgas.json") true)))
(- (count repos) (count (into #{} repos)))
(- (count orgas) (count (into #{} orgas)))
```
on `codegouvfr`, I find 8 dups for the repos and 3 dups for the orgas.

**Comment by bzg** [comment]
Duplicates are now deleted from https://code.etalab.gouv.fr.

**Comment by AntoineAugusti** [comment]
Fixed in https://github.com/etalab/data-codes-sources-fr/pull/44
