### ISSUE TITLE
Pull repositories from Gitlab

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/data-codes-sources-fr#4]

**Comment by AntoineAugusti** [comment]
See https://docs.gitlab.com/ee/api/groups.html#list-a-groups-projects

**Comment by bzg** [comment]
Also see https://github.com/DISIC/politique-de-contribution-open-source/issues/162

**Comment by AntoineAugusti** [comment]
Implemented! Here are the fields always missing for Gitlab repositories because they're not exposed by the API: est_fork, page_accueil, licence, langage

**Comment by AntoineAugusti** [comment]
Licences and langages can be pulled, but it requires 2 calls per project 😢 

- Licence (with flag) https://docs.gitlab.com/ee/api/projects.html#get-single-project
- Languages https://docs.gitlab.com/ee/api/projects.html#languages
