### ISSUE TITLE
Detect a bare GitLab platform

### ISSUE THREAD

**Issue by AntoineAugusti** [etalab/data-codes-sources-fr#40]
It's annoying to maintain [a file](https://github.com/etalab/data-codes-sources-fr/blob/master/platforms.csv) to know the kind of platform behind a URL.

Try to at least detect GitLab platforms, maybe using an API endpoint returning a GitLab specific version.

The file in charge of this is https://github.com/etalab/data-codes-sources-fr/blob/master/platforms.py

cc @bzg, I'm sure you would be happy to stop doing shitty commits updating the CSV

**Comment by bzg** [comment]
> cc @bzg, I'm sure you would be happy to stop doing shitty commits updating the CSV

Yes, I would, but not a high priority, the inconvenience is really bearable.

**Comment by bzg** [comment]
Do you think you can fix this issue in a reasonable time?

**Comment by AntoineAugusti** [comment]
Not sure it's important to work on this now. The CSV file for platforms has not been updated a lot: https://github.com/etalab/data-codes-sources-fr/commits/master/platforms.csv

**Comment by bzg** [comment]
Agreed, feel free to close this one.
