### ISSUE TITLE
https://gitlab.inria.fr/verifisc not appearing in `/api/organisations/all`

### ISSUE THREAD

**Issue by bzg** [etalab/data-codes-sources-fr#45]
In [/api/organisations/all](https://api-code.etalab.gouv.fr/api/organisations/all) I don't see the `verifisc` group, which has been added to [comptes-organismes-publics](https://github.com/DISIC/politique-de-contribution-open-source/blob/master/comptes-organismes-publics) a few days ago.

Strangely enough, `verifisc` is present in the [csv file](https://raw.githubusercontent.com/etalab/data-codes-sources-fr/master/data/organisations/csv/all.csv).

Perhaps this is due to the recent deduplication code?

PS: As a result of this, `mlang` is not listed in https://code.etalab.gouv.fr/fr/repos since code.etalab.gouv.fr relies on the `json`, not the `csv`.

**Comment by AntoineAugusti** [comment]
Hey,

Thanks for flagging this. For some reasons, [the CRON job](https://github.com/etalab/api-codes-sources-fr/blob/master/.circleci/config.yml) stopped working [on CircleCI](https://circleci.com/gh/etalab/api-codes-sources-fr) and the build wasn't triggered anymore on Netlify.

I triggered a build on the other repository, which will solve your issue showing stale data on the API side only. This will solve your issue.

I'll read the CircleCI docs or reach out to understand why the CRON job stopped after some time without a commit activity.

**Comment by bzg** [comment]
Thanks for the quick fix! Feel free to close the issue when you want.

**Comment by AntoineAugusti** [comment]
Asked for clarifications here. According to me this is an undocumented feature of CircleCI.

https://github.com/circleci/circleci-docs/issues/4173
