### ISSUE TITLE
Don't collect all groups from https://git.unistra.fr

### ISSUE THREAD

**Issue by bzg** [etalab/data-codes-sources-fr#46]
The purpose of this issue is to start a discussion on what groups should be listed from https://git.unistra.fr

The next step is to identify the right person at unistra to help us answer this.

**Comment by AntoineAugusti** [comment]
Ping me if you need help on this issue

**Comment by bzg** [comment]
Actually, this is a duplicate of https://github.com/DISIC/politique-de-contribution-open-source/issues/190 - closing it here.
