### ISSUE TITLE
Ensure to list all projects for GitLab org's, even when projects are organized through subgroups

### ISSUE THREAD

**Issue by bzg** [etalab/data-codes-sources-fr#49]
For example, code.etalab.gouv.fr only list [6 projects for gitlab.com/cortext](https://code.etalab.gouv.fr/en/repos?g=https%3A%2F%2Fgitlab.com%2Fcortext) while there are in fact more (e.g. [this one](https://gitlab.com/cortext/cortext-methods/sashimi)).

I guess [this line](https://github.com/etalab/data-codes-sources-fr/blob/master/gitlab.py#L25) is a good starting point, if someone wants to have a look.

**Comment by guillim** [comment]
I think this should be fixed with this PR #51

**Comment by bzg** [comment]
I merged the PR, can you revisit the issue tomorrow and check that the fix is good?

**Comment by guillim** [comment]
Sounds good to me : https://code.etalab.gouv.fr/en/repos?q=cortext => am i right ?

**Comment by bzg** [comment]
Yes!  Great, closing this now. Thanks again.
