### ISSUE TITLE
https://gitub.u-bordeaux.fr repositories are not collected

### ISSUE THREAD

**Issue by bzg** [etalab/data-codes-sources-fr#50]
This is a GitLab instance, declared as such in `platforms.csv` and [comptes-organismes-publics](https://github.com/DISIC/politique-de-contribution-open-source/blob/master/comptes-organismes-publics).

There is no repo matching `gitub` (the missing `h` is intentional) in [repertoires/json/all.json](https://raw.githubusercontent.com/etalab/data-codes-sources-fr/master/data/repertoires/json/all.json).

**Comment by guillim** [comment]
I can see __gitub__ repos in `repertoires/json/all.json`, so : is this issue still _Open_ or can it be closed ? @bzg

**Comment by bzg** [comment]
Mh, yes, I just checked, the repos are here, I'm closing this now. Thanks and sorry for the delay!
