### ISSUE TITLE
Add "nombre_projets" in organizations' metadata

### ISSUE THREAD

**Issue by bzg** [etalab/data-codes-sources-fr#52]
GitLab permet de créer des sous-groupes ou projets à l'intérieur d'un compte d'organisation.

C'est le cas par exemple de https://gitlab.com/DREES_code.

Comme `DREES_code` a zéro dépôt, l'organisation n'est pas affichée par défaut sur https://code.etalab.gouv.fr/fr/groups : nous pourrions corriger ça du côté du frontend en affichant toutes les organisations, même celles qui n'ont pas de dépôt (et ont peut-être des sous-groupes), mais il est sûrement plus efficace de savoir si une organisation a des sous-groupes, et de voir s'il y a moyen de connaître le nombre de dépôts compris dans ces sous-groupes à partir des données disponibles dans l'API de GitLab ou d'une instance GitLab.

**Comment by guillim** [comment]
Voici ce qu'on voit sur code.gouv quand on cherche _drees_: il manque bien l'organisation 
<img width="1121" alt="Screenshot 2021-09-08 at 10 52 04" src="https://user-images.githubusercontent.com/13087916/132478305-d01cf907-87b1-418b-9745-2895fe0b6b14.png">

On voit bien que l'organisation existe mais comme tous les repos sont dans des sous-groupes, il n'apparaissent pas dans code.gouv
<img width="1096" alt="Screenshot 2021-09-08 at 10 52 49" src="https://user-images.githubusercontent.com/13087916/132478420-7f770c88-8a62-4938-b964-fad1bf274d7a.png">

Solution:
Lors de la récupération des repo sur gitlab par le script de code.gouv, il faudrait vérifier que si une organisation n'a pas de repo, elle n’a pas non plus de sous-groupes. Car si elle a des sous-groupes il faut bien l'afficher dans code.gouv

Note: 
checker si l'API de gitlab permet d'obtenir le nbr totatl de repo y compris dans les sous-goupes

Note2 :
English version of this issue 56 
fixes #56

**Comment by bzg** [comment]
I confirm the fix is now reflected in https://code.etalab.gouv.fr/fr/groups?q=drees - thanks!
