### ISSUE TITLE
Pull repositories from FusionForge

### ISSUE THREAD

**Issue by bzg** [etalab/data-codes-sources-fr#6]

**Comment by AntoineAugusti** [comment]
Have you got a URL?

**Comment by bzg** [comment]
https://adullact.net

**Comment by AntoineAugusti** [comment]
There is also a GitLab instance: https://gitlab.adullact.net. Are they going to migrate over there?

**Comment by bzg** [comment]
I don't know. 

I'm copying Matthieu on this (cc @mfaure), working for Adullact, he may have more information for us.

**Comment by AntoineAugusti** [comment]
Documentation: https://scm.fusionforge.org/anonscm/gitweb?p=fusionforge/fusionforge.git;a=tree;f=src/plugins/repositoryapi/Documentation;hb=refs/heads/feature/plugin-repositoryapi-6.0

**Comment by bzg** [comment]
To sum up:

- not all FusionForge instances use the `repositoryapi` API;
- this plugin, when available, does not allow to collect the same metadata than the ones we currently collect from GitHub, gitlab.com and GitLab instances;
- we suggest users of FusionForge tackle this problem together by enhancing this plugin and/or developing a REST API for FusionForge instances.

Possible users are Adullact, INRIA, RENATER and maybe others.

**Comment by bzg** [comment]
We shall consider dismissing this FR.

**Comment by bzg** [comment]
I'm now closing this issue: some agencies are still using a FusionForge instance but they are slowly migrating to GitLab forges, so there is no need to invest time on this.
