### ISSUE TITLE
Expose the list of the last X new repositories as json

### ISSUE THREAD

**Issue by bzg** [etalab/data-codes-sources-fr#8]
The purpose is to build a RSS feed of the latest new repositories referenced by https://github.com/bzg/codegouvfr.

The `json` file would store the name of the repository and the date it has been added to `data-codes-sources-fr`.

**Comment by AntoineAugusti** [comment]
How many?

**Comment by bzg** [comment]
10 seems okay. We'll see if we need more later on.

**Comment by AntoineAugusti** [comment]
Done ✅ 

https://api-codes-sources-fr.antoine-augusti.fr/api/stats/last_repositories

https://github.com/AntoineAugusti/api-codes-sources-fr/commit/2a0bba602c2f854170e3b9ead85b87b52eb26442
